packages:
  - 'apps/*'

allowBuilds:
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@scarf/scarf'
  - 'esbuild'
  - 'msgpackr-extract'
  - 'unrs-resolver'
